branch-defaults:
  default:
    environment: image-filter-starter-code-dev
    group_suffix: null
  master:
    environment: image-filter-starter-code-dev
    group_suffix: null
environment-defaults:
  image-filter-starter-code-dev:
    branch: null
    repository: null
global:
  application_name: image-filter-starter-code
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
